module.exports = {
  arrowParens: 'avoid',
  bracketSameLine: false,
  bracketSpacing: true,
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxSingleQuote: false,
  plugins: ['prettier-plugin-tailwindcss'],
  printWidth: 80,
  proseWrap: 'always',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  plugins: [
    'prettier-plugin-tailwindcss',
    // "@ianvs/prettier-plugin-sort-imports",
  ],
}

// /** @type {import('prettier').Config} */
// module.exports = {
//   endOfLine: "lf",
//   semi: false,
//   singleQuote: false,
//   tabWidth: 2,
//   trailingComma: "es5",
//   importOrder: [
//     "^(react/(.*)$)|^(react$)",
//     "^(next/(.*)$)|^(next$)",
//     "<THIRD_PARTY_MODULES>",
//     "",
//     "^types$",
//     "^@/env(.*)$",
//     "^@/types/(.*)$",
//     "^@/config/(.*)$",
//     "^@/lib/(.*)$",
//     "^@/hooks/(.*)$",
//     "^@/components/ui/(.*)$",
//     "^@/components/(.*)$",
//     "^@/styles/(.*)$",
//     "^@/app/(.*)$",
//     "",
//     "^[./]",
//   ],
//   importOrderSeparation: false,
//   importOrderSortSpecifiers: true,
//   importOrderBuiltinModulesToTop: true,
//   importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
//   importOrderMergeDuplicateImports: true,
//   importOrderCombineTypeAndValueImports: true,
//   plugins: [
//     "@ianvs/prettier-plugin-sort-imports",
//     "prettier-plugin-tailwindcss",
//   ],
// }
